Repository brain-tec/intrastat, pull requests merged in 2024-07, with the labels that each got.

#289 [t140653] Comment not needed migration scripts
  intrastat_base/migrations/16.0.1.0.0/post-migration.py
  intrastat_base/migrations/16.0.1.0.0/pre-migration.py
Labels: 16.0.project_xp_228

#290 [t140653] Add harmonized_system migration script
  product_harmonized_system/migrations/14.0.2.0.0/post-migration.py
Labels: 16.0.project_xp_228

#291 [t140653] Fix migration script
  product_harmonized_system/migrations/14.0.2.0.0/post-migration.py
Labels: 16.0.project_xp_228

#292 [t140653] Delete migration scripts
  intrastat_base/migrations/16.0.1.0.0/post-migration.py
  intrastat_base/migrations/16.0.1.0.0/pre-migration.py
Labels: 16.0.project_xp_228

#293 Syncing from upstream OCA/intrastat-extrastat (17.0)
  .copier-answers.yml
  .eslintrc.yml
  .gitignore
  .pre-commit-config.yaml
Labels: 17.0

#294 Syncing from upstream OCA/intrastat-extrastat (16.0)
  README.md
  intrastat_product/README.rst
  intrastat_product/__manifest__.py
  intrastat_product/models/intrastat_product_declaration.py
  intrastat_product/static/description/index.html
Labels: 16.0
